CREATE TABLE `team_tech_statistics` (
  `team_tech_statistics_id` INT NOT NULL,
  `team_id` INT NULL,
  `competitor_id` INT NULL,
  `date` DATETIME NULL,
  `league_id` INT NULL,
  `season` YEAR NULL,
  `result_id` INT NULL,
  `goal` INT NULL,
  `fumble` INT NULL,
  `assistance` INT NULL,
  `pass` INT NULL,
  `steal` INT NULL,
  `offside` INT NULL,
  `foul` INT NULL,
  `red_card` INT NULL,
  `yellow_card` INT NULL,
  `shoot` INT NULL,
  `shoot_on_goal` INT NULL,
  `shoot_on_goal_rate` INT NULL,
  `success_rate` INT NULL,
  `head_goal` INT NULL,
  `direct_free_goal` INT NULL,
  `penalty_kick_goal` INT NULL,
  `penalty_kick` INT NULL,
  `intercept` INT NULL,
  `rescue` INT NULL,
  `head_rescue` INT NULL,
  `back_field_rescue` INT NULL,
  `success_headers` INT NULL,
  `fail_headers` INT NULL,
  `own_goal` INT NULL,
  `create_time` DATETIME NULL,
  `create_by` VARCHAR(255) NULL,
  `update_time` DATETIME NULL,
  `update_by` VARCHAR(255) NULL,
  PRIMARY KEY (`team_tech_statistics_id`)
)
